version: '3.8'

services:
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: viggo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - ./postgres_data:/bitnami/postgresql
    restart: always
